### ISSUE TITLE
Run fail-fast reporter as a command line argument make it supress needed info

### ISSUE THREAD

**Issue by pitymaia** [MikeBull94/karma-fail-fast-reporter#1]
Hello, when I use fail-fast-reporter by adding the reporter to karma.conf.js I have this console terminal result:

```
$ node_modules/karma/bin/karma start
29 04 2017 22:31:00.979:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
29 04 2017 22:31:00.982:INFO [launcher]: Launching browser Firefox with unlimited concurrency
29 04 2017 22:31:00.993:INFO [launcher]: Starting browser Firefox
29 04 2017 22:31:03.452:INFO [Firefox 53.0.0 (Ubuntu 0.0.0)]: Connected on socket zRI61PCPJnJEOLfZAAAA with id 66900193
Firefox 53.0.0 (Ubuntu 0.0.0): Executed 9 of 9 SUCCESS (0.195 secs / 0.17 secs)
```

Attention to the last line informing that 9 tests passed with success

But when I try to use fail-fast-reporter through the command line the result is this:

```
$ node_modules/karma/bin/karma start --reporters fail-fast
29 04 2017 22:31:42.407:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
29 04 2017 22:31:42.410:INFO [launcher]: Launching browser Firefox with unlimited concurrency
29 04 2017 22:31:42.422:INFO [launcher]: Starting browser Firefox
29 04 2017 22:31:44.935:INFO [Firefox 53.0.0 (Ubuntu 0.0.0)]: Connected on socket BFVnKzhMVGjJSAQwAAAA with id 14405303
```
Notice that the last line has disappeared. This is worse when I try to use along with reporters like the karma-spec-reporter who gives detailed information.
The information on how many tests run and failed always disappears when trying to use fast-fail from the command line.

Karma version: 1.5.0

Thanks for your time.

**Comment by michaelbull** [comment]
I'm not sure why, or if this is even a problem with `karma-fail-fast-reporter`.

If you look at the [default implementation](https://github.com/karma-runner/karma/blob/master/lib/reporters/base.js#L85) of a reporter, it does the exact same thing that [we're doing](https://github.com/michaelbull/karma-fail-fast-reporter/blob/master/index.js#L2). You can see that if its a success or failure it calls an [empty method](https://github.com/karma-runner/karma/blob/master/lib/reporters/base.js#L102), so it's not like we're forgetting to write to the console on a success.

Are you sure that's the correct usage of the Karma CLI? In the command `node_modules/karma/bin/karma start --reporters fail-fast` you don't seem to be specifying a configuration file or any options, so I'm not sure how Karma would know what tests to run.

**Comment by pitymaia** [comment]
Sorry, you're right, it was my mistake. 

The configuration it takes from the default file, it even finds the errors and fails on the first as it should, just dont display de stats. The problem with it is due to the fact that when using the --reporters options on command line I also have to add the "progress" reporter on the command line because it ignores this part of the configuration file if I use the command line option.

The correct command goes like this:

`node_modules/karma/bin/karma start --reporters progress,fail-fast`
